### ISSUE TITLE
`requirements.txt`  includes local paths?

### ISSUE THREAD

**Issue by shanpoyang654** [intuit-ai-research/SPUQ#3]
Thank you for your codes!

But I meet one problem when installing environments using `pip install -r requirements.txt`.
And I found this line as below:
`appnope @ file:///home/conda/feedstock_root/build_artifacts/appnope_1707233003401/work
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work`

Are these packages in your local path?
Can I install these packages directly using `pip install appnope` from standard  PyPI ?

Thank you and hope for your kind reply.

**Comment by golsun** [comment]
hi @shanpoyang654 , thank you for trying out! We just updated requirements.txt
