### ISSUE TITLE
inter-sample confidence

### ISSUE THREAD

**Issue by protecteddivine** [intuit-ai-research/SPUQ#5]
May I ask how is the $$w_i = s(x_0, x_i)$$ in Eq. 1 computed in the code? It seems like there's no reweighing in the InterSampleAggregation class.

**Comment by golsun** [comment]
hi @protecteddivine 
Thank you for noticing this. We missed it during our code refactoring. We have just updated the code, and w_i is now calculated [here](https://github.com/intuit-ai-research/SPUQ/blob/main/aggregation.py#L100) using text similarity.
